//! Protocol wire message types.
//!
//! All messages are serializable. The fields are documented with their
//! protocol security role. Receivers must validate all fields before acting.

use serde::{Deserialize, Serialize};
use tls_attestation_attestation::{
    engine::AttestationPackage,
    envelope::AttestationEnvelope,
    statement::StatementPayload,
};
use tls_attestation_core::{
    hash::DigestBytes,
    ids::{ProverId, SessionId, VerifierId},
    types::{Epoch, Nonce, QuorumSpec, UnixTimestamp},
};
use tls_attestation_crypto::participant_registry::RegistryEpoch;
use tls_attestation_crypto::randomness::PartialRandomness;
use tls_attestation_crypto::threshold::PartialSignature;

/// Sent by the prover to the coordinator to initiate attestation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttestationRequest {
    /// The prover's identity.
    pub prover_id: ProverId,
    /// Client-provided nonce contribution (mixed with coordinator nonce).
    /// Allows the prover to contribute entropy to the session freshness.
    pub client_nonce: Nonce,
    /// Application-defined statement type tag.
    pub statement_tag: String,
    /// Raw query bytes to be attested.
    pub query: Vec<u8>,
    /// Optional expiry hint (seconds from now). Coordinator may cap this.
    pub requested_ttl_secs: u64,
}

/// Sent by the coordinator to all verifiers to initialize a session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionInitMsg {
    pub session_id: SessionId,
    pub prover_id: ProverId,
    pub coordinator_id: VerifierId,
    pub quorum: QuorumSpec,
    pub epoch: Epoch,
    pub created_at: UnixTimestamp,
    pub expires_at: UnixTimestamp,
    /// Session nonce generated by the coordinator.
    /// Security: must be fresh and unpredictable.
    pub nonce: Nonce,
}

/// A verifier's partial randomness contribution, sent to the coordinator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartialRandomnessMsg {
    pub session_id: SessionId,
    pub verifier_id: VerifierId,
    pub partial: PartialRandomness,
}

/// Sent by the coordinator to aux verifiers for independent validation.
///
/// The aux verifier recomputes all digests from the package and statement
/// fields. It does NOT trust the coordinator's claimed values.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationRequestMsg {
    pub session_id: SessionId,
    pub package: AttestationPackage,
    pub statement: StatementPayload,
    /// The envelope digest the coordinator computed. Aux verifiers must
    /// recompute this independently and refuse to sign if it disagrees.
    pub claimed_envelope_digest: DigestBytes,
}

/// Sent by an aux verifier to the coordinator after checking the package.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationResponseMsg {
    pub session_id: SessionId,
    pub verifier_id: VerifierId,
    /// Present iff the verifier approved the package.
    pub partial_signature: Option<PartialSignature>,
    /// If None, the verifier approved. If Some, explains the rejection.
    pub rejection_reason: Option<String>,
}

/// The final attestation result, returned to the prover.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AttestationResponse {
    Success(AttestationEnvelope),
    Failure {
        session_id: SessionId,
        reason: String,
    },
}

// ── FROST two-round distributed signing messages ──────────────────────────────
//
// These four messages implement the distributed FROST protocol wire format.
// They are only compiled when the `frost` feature is enabled.
//
// Security properties:
//
// - `FrostRound1Request` carries `signed_digest` and `envelope_digest` so the
//   recipient can verify `signed_digest == approval_signed_digest(envelope_digest)`
//   before generating nonces and commitments.
//
// - `signer_set` is fixed in Round 1 and echoed unchanged in Round 2.
//   Aux verifiers reject Round-2 requests where `signer_set` differs.
//
// - `signing_package_bytes` in `FrostRound2Request` embeds the message
//   (the signed_digest) and all Round-1 commitments.  Aux verifiers verify
//   `signing_package.message() == cached_signed_digest` before signing.
//
// - All FROST-specific bytes (`commitment_bytes`, `signing_package_bytes`,
//   `signature_share_bytes`) are opaque outside `tls_attestation_crypto::frost_adapter`.

/// Sent by the coordinator to each selected auxiliary verifier to initiate Round 1.
///
/// The recipient must:
/// 1. Verify it is included in `signer_set`.
/// 2. Verify `signed_digest == approval_signed_digest(envelope_digest)`.
/// 3. Verify `round_expires_at` has not passed.
/// 4. If `hsp_proof_bytes` is non-empty, verify the HSP Groth16 proof
///    (paper §VIII.B: `{0,1} ← ZKP.Verify(π_HSP, rand)`) before accepting.
/// 5. Generate fresh nonces, store them locally (never transmitted).
/// 6. Return its `SigningCommitments` in `FrostRound1Response`.
#[cfg(feature = "frost")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FrostRound1Request {
    pub session_id: SessionId,
    /// Identity of the coordinator sending this request.
    /// Verifiers may use this for mutual authentication in production.
    pub coordinator_id: VerifierId,
    /// Domain-separated signed digest: `approval_signed_digest(envelope_digest)`.
    /// This is the exact bytes that will appear as the message in the
    /// `SigningPackage` — verifiers must check this in Round 2.
    pub signed_digest: DigestBytes,
    /// Raw envelope digest. Verifiers must check
    /// `approval_signed_digest(envelope_digest) == signed_digest`
    /// before generating nonces.
    pub envelope_digest: DigestBytes,
    /// Participants selected for this signing session.
    /// Fixed for both rounds — verifiers reject Round-2 requests with a
    /// different set.
    pub signer_set: Vec<VerifierId>,
    /// Latest timestamp at which this round is still valid.
    /// Verifiers reject stale requests (session TTL enforcement).
    pub round_expires_at: UnixTimestamp,
    /// The `ParticipantRegistry` epoch this signing session is bound to.
    ///
    /// Aux nodes that hold a `ParticipantRegistry` validate that this epoch
    /// matches their registry's epoch and that all `signer_set` members are
    /// `Active` at that epoch.  `RegistryEpoch::GENESIS` signals the legacy
    /// (no-registry) path, which skips epoch and status checks.
    pub registry_epoch: RegistryEpoch,
    /// Serialized `HspProof` for the dx-DCTLS handshake (π_HSP).
    ///
    /// When non-empty, each auxiliary verifier runs Groth16 verification
    /// (`ZKP.Verify(π_HSP, rand)`) before generating its Round-1 commitment,
    /// implementing the check from paper §VIII.B (Signing Phase, step 3).
    ///
    /// Empty for legacy sessions that do not carry an HSP proof.
    #[serde(default)]
    pub hsp_proof_bytes: Vec<u8>,
    /// Serialized Groth16 processed verifying key for the HSP circuit.
    ///
    /// Coordinator distributes this once; aux verifiers use it to run
    /// `ZKP.Verify(π_HSP, rand)` without recomputing the trusted setup.
    /// Empty when `hsp_proof_bytes` is empty.
    #[serde(default)]
    pub hsp_pvk_bytes: Vec<u8>,

    /// Serialized `DctlsEvidence` for π_DCTLS and π_pgp verification.
    ///
    /// When non-empty, aux verifiers run two additional checks from
    /// paper §VIII.B (Signing Phase, steps 4-5):
    ///
    ///   `ZKP.Verify(π_DCTLS, rand) = 1`  — commitment chain consistency
    ///   `ZKP.Verify(π_pgp, b) = 1`        — PGP binding to HSP + QP transcript
    ///
    /// These checks confirm that:
    /// 1. The HSP, QP, and PGP proofs all reference the same session and rand.
    /// 2. The PGP commitment correctly binds the query/response statement
    ///    to the TLS session identified by the HSP proof.
    ///
    /// Verification is commitment-based (SHA256 hash chain), not ZK.
    /// No plaintext query/response data is exposed to aux verifiers.
    /// Empty for legacy sessions.
    #[serde(default)]
    pub dctls_evidence_bytes: Vec<u8>,

    /// DVRF randomness output (`rand_value`) for the session.
    ///
    /// Required alongside `dctls_evidence_bytes` for π_DCTLS verification.
    /// Aux verifiers check that HSP and QP proofs both reference this value,
    /// binding the TLS session to the DVRF output they computed.
    #[serde(default)]
    pub rand_value_bytes: Vec<u8>,

    /// TLS server certificate hash for the session.
    ///
    /// Required for π_DCTLS verification — confirms the TLS session used
    /// the expected server certificate (anti-impersonation).
    #[serde(default)]
    pub server_cert_hash_bytes: Vec<u8>,
}

/// Sent by an auxiliary verifier to the coordinator after completing Round 1.
///
/// `commitment_bytes` is the serialized `SigningCommitments` from
/// `FrostCommitment::to_bytes()`.  The coordinator deserializes it via
/// `FrostCommitment::from_bytes` to build the `SigningPackage`.
#[cfg(feature = "frost")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FrostRound1Response {
    pub session_id: SessionId,
    pub verifier_id: VerifierId,
    /// Serialized `SigningCommitments` — opaque outside `frost_adapter`.
    pub commitment_bytes: Vec<u8>,
}

/// Sent by the coordinator to each Round-1 participant to trigger Round 2.
///
/// The recipient must:
/// 1. Verify it participated in Round 1 for this session (nonces cached).
/// 2. Verify `signer_set` exactly matches the set committed in Round 1.
/// 3. Deserialize `signing_package_bytes` and verify its embedded message
///    equals the `signed_digest` cached during Round 1.
/// 4. Consume the cached nonces and produce a `SignatureShare`.
#[cfg(feature = "frost")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FrostRound2Request {
    pub session_id: SessionId,
    pub coordinator_id: VerifierId,
    /// Serialized `SigningPackage` — opaque outside `frost_adapter`.
    /// Contains the message (`signed_digest`) and all Round-1 commitments.
    pub signing_package_bytes: Vec<u8>,
    /// Signer set from Round 1. Must match the set stored during Round 1
    /// exactly — verifiers reject requests where this has changed.
    pub signer_set: Vec<VerifierId>,
}

/// Sent by an auxiliary verifier to the coordinator after completing Round 2.
///
/// `signature_share_bytes` is the serialized `SignatureShare` from
/// `FrostSignatureShare::to_bytes()`.  The coordinator aggregates all shares
/// via `aggregate_signature_shares`.
#[cfg(feature = "frost")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FrostRound2Response {
    pub session_id: SessionId,
    pub verifier_id: VerifierId,
    /// Serialized `SignatureShare` — opaque outside `frost_adapter`.
    pub signature_share_bytes: Vec<u8>,
}

// ── Handshake 2PC binding messages ───────────────────────────────────────────
//
// These four messages implement the Handshake 2PC sub-protocol.
//
// After the coordinator completes the TLS handshake it holds:
//   cert_hash, tls_version, server_name, established_at, session_nonce
//
// It computes a `binding_input`:
//   H("tls-attestation/2pc-binding/v1"
//     || session_id || rand_value || cert_hash
//     || tls_version[u64] || server_name[len-prefixed] || session_nonce)
//
// Then runs a mini FROST protocol over `binding_input`, producing a 64-byte
// aggregate signature σ.  The threshold-locked exporter is:
//   dvrf_exporter = H("tls-attestation/2pc-exporter/v1" || σ)
//
// Security guarantee: deriving `dvrf_exporter` requires both a real TLS
// session (for `session_nonce`) AND cooperation of t-of-n aux nodes.
// A compromised coordinator cannot forge it unilaterally.

/// Round 1 of the Handshake Binding protocol.
///
/// The coordinator sends the `binding_input` (the domain-separated hash of
/// TLS session parameters) along with the signer set and an expiry.
/// Aux nodes must:
///   1. Verify they are in `signer_set`.
///   2. Verify `round_expires_at` has not passed.
///   3. Generate fresh nonces, store them keyed by `(session_id, "hb")`.
///   4. Return their `SigningCommitments`.
#[cfg(feature = "frost")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandshakeBindingRound1Request {
    pub session_id: SessionId,
    pub coordinator_id: VerifierId,
    /// `H("tls-attestation/2pc-binding/v1" || session_id || rand_value
    ///    || cert_hash || tls_version || server_name || session_nonce)`
    ///
    /// This is the exact bytes that will be signed in Round 2.
    /// Aux nodes cache it and verify it matches the SigningPackage in Round 2.
    pub binding_input: DigestBytes,
    pub signer_set: Vec<VerifierId>,
    pub round_expires_at: UnixTimestamp,
    pub registry_epoch: RegistryEpoch,
}

/// Aux node → coordinator after completing Handshake Binding Round 1.
#[cfg(feature = "frost")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandshakeBindingRound1Response {
    pub session_id: SessionId,
    pub verifier_id: VerifierId,
    /// Serialized `SigningCommitments`.
    pub commitment_bytes: Vec<u8>,
}

/// Round 2 of the Handshake Binding protocol.
///
/// The coordinator assembles the `SigningPackage` from all Round-1 commitments
/// and sends it to each participant.  Aux nodes must:
///   1. Verify the `SigningPackage` message equals the cached `binding_input`.
///   2. Verify `signer_set` matches the set from Round 1.
///   3. Produce and return a `SignatureShare`.
#[cfg(feature = "frost")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandshakeBindingRound2Request {
    pub session_id: SessionId,
    pub coordinator_id: VerifierId,
    /// Serialized `SigningPackage` embedding `binding_input` as message.
    pub signing_package_bytes: Vec<u8>,
    pub signer_set: Vec<VerifierId>,
}

/// Aux node → coordinator after completing Handshake Binding Round 2.
#[cfg(feature = "frost")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandshakeBindingRound2Response {
    pub session_id: SessionId,
    pub verifier_id: VerifierId,
    /// Serialized `SignatureShare`.
    pub signature_share_bytes: Vec<u8>,
}

// ── DKG ceremony wire messages ─────────────────────────────────────────────────
//
// Used by the `dkg_node` coordinator to orchestrate a Pedersen DKG ceremony
// over the network.  Message flow:
//
//   Coordinator → all: DkgCeremonyAnnouncement
//   Participant → coordinator: DkgRound1Response (broadcast package)
//   Coordinator → each participant: DkgRound2Delivery (encrypted unicast packages)
//   Participant → coordinator: DkgPart3Response (ceremony result / group key)
//
// All Round-2 packages are X25519+XChaCha20-Poly1305 encrypted (see
// `tls_attestation_crypto::dkg_encrypt`) — the coordinator routes ciphertexts
// and cannot read plaintext secret-sharing material.

/// Coordinator → all: initiates a Pedersen DKG ceremony.
///
/// All participants receive the same announcement, establishing a shared view
/// of the ceremony parameters before Part 1 begins.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DkgCeremonyAnnouncement {
    /// Fresh random identifier binding all packages to this ceremony.
    /// Prevents cross-ceremony package replay.
    pub ceremony_id: Vec<u8>,
    /// Ordered list of all participants (same ordering for all nodes).
    /// Position in list determines FROST identifier (index + 1).
    pub all_participant_ids: Vec<VerifierId>,
    /// Signing threshold (min_signers).
    pub min_signers: u16,
    /// X25519 encryption public keys, one per participant in the same order as
    /// `all_participant_ids`.  Each participant uses its counterpart's key to
    /// encrypt Round-2 packages.
    pub encryption_public_keys: Vec<Vec<u8>>,
}

/// Participant → coordinator after DKG Part 1.
///
/// The coordinator collects one of these from every participant, then
/// distributes the full set (minus each sender's own) for Part 2.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DkgRound1Response {
    pub ceremony_id: Vec<u8>,
    pub participant_id: VerifierId,
    /// Serialized `DkgRound1Package` (serde_json of the FROST type).
    pub round1_package_bytes: Vec<u8>,
}

/// Coordinator → participant: delivers all encrypted Round-2 unicast packages
/// addressed to this participant.
///
/// Each entry in `encrypted_packages` is `(sender_id, ciphertext_bytes)`.
/// The recipient decrypts each with its X25519 private key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DkgRound2Delivery {
    pub ceremony_id: Vec<u8>,
    pub recipient_id: VerifierId,
    /// Encrypted Round-2 packages sent to this participant.
    /// Format: `(sender_id, serde_json(EncryptedDkgRound2Package))`.
    pub encrypted_packages: Vec<(VerifierId, Vec<u8>)>,
}

/// Participant → coordinator after DKG Part 3 (final).
///
/// Carries the serialized group verifying key so the coordinator can confirm
/// all participants derived the same key before announcing ceremony success.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DkgPart3Response {
    pub ceremony_id: Vec<u8>,
    pub participant_id: VerifierId,
    /// Serialized group verifying key bytes (coordinator cross-checks all match).
    pub group_key_bytes: Vec<u8>,
    /// `true` if Part 3 succeeded; `false` if the participant rejected inputs.
    pub success: bool,
    /// Human-readable error description when `success = false`.
    pub error_message: Option<String>,
}
