// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/FrostVerifier.sol";

/**
 * @title FrostVerifierTest
 * @notice Tests for the secp256k1 FROST Schnorr signature verifier.
 *
 * Test vectors produced by:
 *   cargo run --bin gen-test-vectors --features frost,tcp,secp256k1
 *
 * Scheme : FROST(secp256k1, SHA-256), 2-of-3 threshold
 * Message: sha256("test attestation for dx-DCTLS")
 */
contract FrostVerifierTest is Test {

    FrostVerifier verifier;

    // ── Test vectors ─────────────────────────────────────────────────────────

    // sha256("test attestation for dx-DCTLS")
    bytes32 constant MSG_HASH =
        0x3ad1c26fe3af0a4b71801794e81e542d3ac0f4564d853a3f810fc9054c1e63b9;

    // Key pair generated by gen-test-vectors (keccak256-Schnorr, matches FrostVerifier.sol)
    uint256 constant PK_X =
        0xb97c578946b0f92ba4c778f43ef2824a1336c0b5df4d3f512362d8e4321c5bed;
    uint256 constant PK_Y =
        0x90670a4719489ef730572fc9d3b225b08b5384184bca8c5ad7497d6f6ff46b0b;

    // Schnorr signature (R_x, s) — even-y convention
    // Challenge e = keccak256(R_x || pk_x || msg) % N
    uint256 constant SIG_R_X =
        0xfb63cd658833e1ad29509d4b81aefe470aec1f08231f3f85385edec6528ba2fd;
    uint256 constant SIG_S =
        0xe2952fc3730fb0157a8086e88896f6e261f32fe1d641b27527509d4756fc9265;

    // ── Setup ─────────────────────────────────────────────────────────────────

    function setUp() public {
        verifier = new FrostVerifier();
    }

    // ── Deployment ────────────────────────────────────────────────────────────

    function test_Deploy() public view {
        assertTrue(address(verifier) != address(0));
    }

    // ── Valid signature ───────────────────────────────────────────────────────

    function test_ValidSignature() public view {
        bool valid = verifier.verify(MSG_HASH, PK_X, PK_Y, SIG_R_X, SIG_S);
        assertTrue(valid, "valid FROST signature should verify");
    }

    // ── Invalid inputs ────────────────────────────────────────────────────────

    function test_WrongMessage() public view {
        bytes32 wrongHash = keccak256("wrong message");
        bool valid = verifier.verify(wrongHash, PK_X, PK_Y, SIG_R_X, SIG_S);
        assertFalse(valid, "wrong message should not verify");
    }

    function test_WrongSigS() public view {
        uint256 badS = SIG_S ^ 1;
        bool valid = verifier.verify(MSG_HASH, PK_X, PK_Y, SIG_R_X, badS);
        assertFalse(valid, "corrupted s should not verify");
    }

    function test_WrongRx() public view {
        uint256 badRx = SIG_R_X ^ 1;
        bool valid = verifier.verify(MSG_HASH, PK_X, PK_Y, badRx, SIG_S);
        assertFalse(valid, "wrong R_x should not verify");
    }

    function test_WrongPubKeyX() public view {
        uint256 badPkX = PK_X ^ 1;
        bool valid = verifier.verify(MSG_HASH, badPkX, PK_Y, SIG_R_X, SIG_S);
        assertFalse(valid, "wrong public key x should not verify");
    }

    function test_ZeroSignature() public view {
        bool valid = verifier.verify(MSG_HASH, PK_X, PK_Y, 0, 0);
        assertFalse(valid, "zero signature should not verify");
    }

    // ── Gas measurement ───────────────────────────────────────────────────────

    /// Paper §IX: ~4,200 gas for 2 ECMUL + 2 ECADD on secp256k1.
    function test_GasCost() public {
        uint256 before = gasleft();
        verifier.verify(MSG_HASH, PK_X, PK_Y, SIG_R_X, SIG_S);
        uint256 used = before - gasleft();
        emit log_named_uint("FrostVerifier.verify gas", used);
        assertLt(used, 50_000, "verify should use < 50k gas");
    }
}